services:
  llamafactory:
    build:
      dockerfile: ./docker/docker-cuda/Dockerfile
      context: ../..
      args:
        INSTALL_BNB: "false"
        INSTALL_VLLM: "false"
        INSTALL_DEEPSPEED: "false"
        INSTALL_FLASHATTN: "false"
        INSTALL_LIGER_KERNEL: "false"
        INSTALL_HQQ: "false"
        INSTALL_EETQ: "false"
        PIP_INDEX: https://pypi.org/simple
    container_name: llamafactory-changdu
    volumes:
      - ../../hf_cache:/root/.cache/huggingface
      - ../../ms_cache:/root/.cache/modelscope
      - ../../om_cache:/root/.cache/openmind
      - ../../data:/app/data
      - ../../output:/app/output
      - ../../saves:/app/saves
    ports:
      - "7886:7860"
      - "8600:8000"
      - "8887:8887"
      - "8888:8888"
      - "8889:8889"
    ipc: host
    tty: true
    shm_size: "16gb"
    stdin_open: true
    command: ['export', 'HF_ENDPOINT="https://hf-mirror.com"', '&&', 'bash']
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: "all"
            capabilities: [gpu]
    restart: unless-stopped
